codecov:
  branch: main
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
comment:
  behavior: default
  layout: header,tree
  require_changes: false
coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    changes: false
    patch: false
    project:
      default:
        threshold: 1%
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
  javascript:
    enable_partials: false
