# Fetch this API to get the latest IBAN registry data from Wikipedia. Place the JSON response body in a 
# new file 'api-result-{RevId}.json' where {RevId} is the revision id of the page (this can be found in the 
# response body. Then, update the attribute on the WikipediaRegistryProvider.Load method. On the next 
# project rebuild, the new provider will be generated.
GET https://en.wikipedia.org/w/api.php?format=json&action=parse&page=International_Bank_Account_Number&section=16
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36

###

GET https://en.wikipedia.org/api/rest_v1/page/html/International_Bank_Account_Number
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36
